name: Release on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Production Build
        run: |
          npm ci
          npm run build

      - name: Archive Production Build
        run: |
          zip -r chrome-extension-close-tabs-${{github.ref_name}}.zip ./dist

      - name: Create Release
        run: |
          gh release create ${{github.ref_name}} --generate-notes ${{github.ref_name}}.tar.gz
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}